### Python

In [2]:
print("Hello World") ## String should be defined with inverted comma

Hello World


In [3]:
!python --version

Python 3.8.8


In [4]:
5+12-3

14

In [5]:
a=5
b=8
c=a+b

In [6]:
a=5
b=8
c=a+b
c

13

In [8]:
x=17
y=21
sub=x-y
sub

-4

### Variables

In [ ]:
## Store some values

In [5]:
name = "Utkarsh" ### It is case sensetive.
name

'Utkarsh'

In [6]:
name@ = "Utkarsh"  ### Only allowed special character is underscore only.

SyntaxError: invalid syntax (<ipython-input-6-a872953733fa>, line 1)

### Data Type

In [7]:
a = "Utkarsh"
type(a)

str

In [14]:
b =5.2
type(b)

float

In [15]:
c =3
type(c)

int

In [18]:
d=2+3j
type(d)

complex

In [19]:
x = True
type(x)

bool

In [20]:
x ="True"
type(x)

str

### List
1. Allows Hetrogenous
2. Index start from 0
3. Mutable using Index
4. []

In [21]:
sample_list = [12,43,56,"hi",1+2j,6.7]
sample_list

[12, 43, 56, 'hi', (1+2j), 6.7]

In [22]:
type(sample_list)

list

In [23]:
sample_list[0]

12

In [24]:
sample_list[2]

56

In [25]:
sample_list[20]

IndexError: list index out of range

In [27]:
sample_list[2]=3.5
sample_list

[12, 43, 3.5, 'hi', (1+2j), 6.7]

In [30]:
sample_list.reverse()
sample_list

[12, 43, 3.5, 'hi', (1+2j), 6.7]

In [33]:
sample_list

[3.5, 12, 43, 'hi', (1+2j), 6.7]

In [35]:
sample_list[3]=5
sample_list[4]=6
sample_list

[3.5, 12, 43, 5, 6, 6.7]

In [36]:
sample_list.sort()
sample_list

[3.5, 5, 6, 6.7, 12, 43]

### Tuple
1. Allows Hetrogenous
2. Not Mutable
3. Index start from 0 and Retrieve using Index
4. ()

In [38]:
sample_tuple= (1,56,3.5,"hi",1+2j)  ### Tuple is hetrogenous- can allow multiple data type
sample_tuple

(1, 56, 3.5, 'hi', (1+2j))

In [39]:
sample_tuple = 1,56,3.5,"hi",1+2j
sample_tuple

(1, 56, 3.5, 'hi', (1+2j))

In [40]:
type(sample_tuple)

tuple

In [41]:
sample_tuple[2]

3.5

In [43]:
sample_tuple.reverse()

AttributeError: 'tuple' object has no attribute 'reverse'

In [44]:
sample_tuple[3]

'hi'

In [45]:
sample_tuple[3]=5

TypeError: 'tuple' object does not support item assignment

In [46]:
sample_tuple.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [47]:
sample_tuple.remove("hi")

AttributeError: 'tuple' object has no attribute 'remove'

### Set
1. Add Hetrogenous
2. Immutable using Index, mutable using element
3. Does not allow duplicate
4. Cannot access using index
5. Order-first place

In [48]:
sample_set = {1,123,43,23,45,67,22,21,32,0,25,3,66,66,0,23,43,1,"hi","fox","a","abc",252}
type(sample_set)

set

In [49]:
sample_set

{0,
 1,
 123,
 21,
 22,
 23,
 25,
 252,
 3,
 32,
 43,
 45,
 66,
 67,
 'a',
 'abc',
 'fox',
 'hi'}

In [50]:
sample_set[2]

TypeError: 'set' object is not subscriptable

In [51]:
sample_set.remove(43)
sample_set

{0, 1, 123, 21, 22, 23, 25, 252, 3, 32, 45, 66, 67, 'a', 'abc', 'fox', 'hi'}

In [52]:
sample_set.add(99)
sample_set

{0,
 1,
 123,
 21,
 22,
 23,
 25,
 252,
 3,
 32,
 45,
 66,
 67,
 99,
 'a',
 'abc',
 'fox',
 'hi'}

In [53]:
sample_set.add(99,102)

TypeError: add() takes exactly one argument (2 given)

In [56]:
sample_set.pop()  ### pops randomly picks an element

0

### Dictonary
1. Has key value pair datastructure
2. key is unique and values can be duplicated
3. Can retrive the value using key
4. Can change the value using key
5. Key is immutable

In [58]:
sample_dict = {"a":"alpha",1:"first",2:"second",3:"third",1:"forth",5:"forth",6:"sixth"}
type(sample_dict)


dict

In [59]:
sample_dict ### Key is unique/vale can be duplicated

{'a': 'alpha', 1: 'forth', 2: 'second', 3: 'third', 5: 'forth', 6: 'sixth'}

In [60]:
sample_dict["a"]

'alpha'

In [61]:
sample_dict[5]  ###retrive the value using key

'forth'

In [62]:
sample_dict[alpha]   ### Key cannot be retrived using value

NameError: name 'alpha' is not defined

In [65]:
sample_dict[5]= "fifth"  ###mutable using key
sample_dict

{'a': 'alpha', 1: 'forth', 2: 'second', 3: 'third', 5: 'fifth', 6: 'sixth'}

In [66]:
sample_dict["alpha"] = 1
sample_dict

{'a': 'alpha',
 1: 'forth',
 2: 'second',
 3: 'third',
 5: 'fifth',
 6: 'sixth',
 'alpha': 1}

In [67]:
sample_dict[7] = "seventh"  ### We can add key and value to the dictonary
sample_dict

{'a': 'alpha',
 1: 'forth',
 2: 'second',
 3: 'third',
 5: 'fifth',
 6: 'sixth',
 'alpha': 1,
 7: 'seventh'}

In [68]:
sample_dict.reverse()
sample_dict

AttributeError: 'dict' object has no attribute 'reverse'

### String
1. String can be retrived using index
2. String is immutable

In [71]:
a = "hi how are you ?"
type(a)

str

In [72]:
a[1]

'i'

In [73]:
a[10]

' '

In [74]:
a[3]= 10

TypeError: 'str' object does not support item assignment

### Numpy: Package for Multidimensional array

Vectors(1d)

Matrix (2d or 1d)

### Create an array

In [76]:
import numpy as np

In [77]:
simple_list=[6,2,9]
np.array(simple_list)

array([6, 2, 9])

In [79]:
arr=np.array(simple_list)
arr

array([6, 2, 9])

In [80]:
list_of_list=[[6,2,9],[21,8,3],[28,8,0]]
np.array(list_of_list)

array([[ 6,  2,  9],
       [21,  8,  3],
       [28,  8,  0]])

In [81]:
arr=np.array(list_of_list)
arr

array([[ 6,  2,  9],
       [21,  8,  3],
       [28,  8,  0]])

In [85]:
arr=np.array([[6,2,9],[21,8,3]])
arr

array([[ 6,  2,  9],
       [21,  8,  3]])

In [88]:
arr=np.array([[6,2,9],[21,8,3],[28,8,0]])
arr

array([[ 6,  2,  9],
       [21,  8,  3],
       [28,  8,  0]])

In [92]:
np.arange(6,9)

array([6, 7, 8])

In [93]:
np.arange(6,40,6)

array([ 6, 12, 18, 24, 30, 36])

In [94]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [95]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [98]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [99]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [100]:
import numpy as np

In [101]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [102]:
np.linspace(0,2,30)

array([0.        , 0.06896552, 0.13793103, 0.20689655, 0.27586207,
       0.34482759, 0.4137931 , 0.48275862, 0.55172414, 0.62068966,
       0.68965517, 0.75862069, 0.82758621, 0.89655172, 0.96551724,
       1.03448276, 1.10344828, 1.17241379, 1.24137931, 1.31034483,
       1.37931034, 1.44827586, 1.51724138, 1.5862069 , 1.65517241,
       1.72413793, 1.79310345, 1.86206897, 1.93103448, 2.        ])

In [103]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [104]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
np.random.rand(3,5)  ### Uniform distribution b/w 0 to 1

array([[0.7251194 , 0.55736831, 0.1611389 , 0.56053061, 0.42772532],
       [0.51033627, 0.93516803, 0.79223171, 0.95805825, 0.95098165],
       [0.1485968 , 0.46161179, 0.1151929 , 0.53452041, 0.00655973]])

In [106]:
np.random.randint(0,10,100)

array([9, 0, 4, 5, 1, 0, 9, 2, 2, 9, 4, 6, 4, 1, 8, 4, 1, 9, 1, 4, 3, 2,
       8, 1, 8, 9, 1, 9, 5, 3, 7, 2, 4, 7, 1, 4, 8, 8, 9, 5, 1, 5, 4, 0,
       7, 7, 3, 6, 0, 3, 9, 8, 2, 9, 5, 1, 2, 1, 6, 7, 1, 7, 8, 4, 5, 2,
       6, 6, 1, 7, 1, 1, 9, 9, 2, 9, 4, 6, 2, 3, 4, 3, 9, 1, 3, 1, 3, 7,
       3, 8, 8, 1, 0, 2, 2, 0, 3, 1, 2, 4])

In [108]:
np.random.randint(2,99,6)

array([95, 19,  6, 80, 54, 33])

In [110]:
sample_array=np.arange(6,99)
sample_array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94, 95, 96, 97, 98])

In [113]:
rand_array=np.random.randint(6,99,9)
rand_array

array([70, 48, 48, 22, 73, 68, 31, 80,  8])

In [114]:
sample_array.min()

6

In [115]:
sample_array.argmin()

0

In [116]:
rand_array.argmin()

8

In [117]:
rand_array.max()

80

In [118]:
rand_array.argmax()

7

In [119]:
sample_array.argmax()

92

In [120]:
sample_array.dtype

dtype('int32')

In [121]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [124]:
a=np.random.rand(2,5)
a

array([[0.74138795, 0.56115972, 0.99637135, 0.23316798, 0.22686791],
       [0.38693931, 0.16328944, 0.89718949, 0.89631152, 0.16717398]])

In [125]:
a.T

array([[0.74138795, 0.38693931],
       [0.56115972, 0.16328944],
       [0.99637135, 0.89718949],
       [0.23316798, 0.89631152],
       [0.22686791, 0.16717398]])

In [130]:
sample_array=np.arange(9,27)
sample_array

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26])

In [136]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [137]:
sample_array=sample_array.reshape(5,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (5,4)

In [138]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [139]:
sample_array[5]=100
sample_array

array([[  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [100, 100, 100]])

In [140]:
sample_array=np.arange(9,99)
sample_array

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
       94, 95, 96, 97, 98])

In [141]:
sample_array[1:13]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [142]:
sample_array[6:19]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [144]:
a=sample_array[0:12]
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [146]:
sample_array[:] = 1002
sample_array

array([1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1002,
       1002, 1002])